name: deploy-logic-app
parameters:
- name: azureServiceConnection
  type: string
  default: '$(connection)'
variables:
  - template: ./global.yml
  - name: 'location'
    value: 'uksouth'
  - name: templateFile
    value: '$(Build.SourcesDirectory)/bicep/modules/apimlogicapp.bicep'
  - name: csmParametersFile
    value: '$(Build.SourcesDirectory)/bicep/modules/apimlogicapp.dev.bicepparam'
  - group: 'ais-connection-vars-dev'
trigger: none
resources:
  pipelines:
  - pipeline: package-logic-app
    source: package-logic-app
stages:
  - stage: Dev
    jobs:
    - deployment: Dev_Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: ./print-env.yml
            - template: deploy.yml
              parameters:
                logicAppName: 'la-aisv31-dev'
                artifactName: '$(artifactName)'
                serviceConnectionName: $(connection)
                logicAppBuildPipelineLabel: $(logicAppBuildPipelineLabel)
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Subscription'
                ConnectedServiceName: '${{ parameters.azureServiceConnection }}'
                SubscriptionName: '$(subscription-name)' #This var is from the library
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'rg-apim-aisv31-dev' #This var is from the library
                location: '$(location)'
                templateLocation: 'Linked artifact'
                csmFile: '$(templateFile)'
                csmParametersFile: '$(csmParametersFile)'
                #overrideParameters: '-storageAccountType Standard_LRS'
                deploymentMode: 'Incremental'
                deploymentName: 'DeployPipelineTemplate'