# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Logic App. 

env:
    AZURE_LOGICAPP_PACKAGE_PATH: '.'
    RG_LA_DEV: ${{ vars.RG_PREFIX}}dev
    RG_LA_TEST: ${{ vars.RG_PREFIX}}test
  
on: 
  workflow_dispatch:

jobs:
  logic_app_dev_build: 
    runs-on: ubuntu-latest
    environment:
        name: dev
    steps: 

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    # Create resource group
    - name: Create resource group
      run: |
        az group create \
        --name ${{env.RG_LA_DEV}} \
        --location ${{vars.LOCATION}} 

    # Deploy Bicep file
    - name: Deploy Bicep
      id: bicep
      run: |
        az deployment group create \
        --name 'bicep-deploy-'${{ github.run_id }} \
        --resource-group ${{env.RG_LA_DEV}} \
        --parameters bicep/main.dev.bicepparam

    - name: Get output
      id: output_step
      run: |
        logicAppName=$(az deployment group show --name bicep-deploy-${{ github.run_id }} --resource-group ${{env.RG_LA_DEV}} --query properties.outputs.logicAppName.value -o tsv)
        echo "logicAppName = $logicAppName"
        echo "logicAppName=$logicAppName" >> $GITHUB_OUTPUT  
    
    - name: "Trace logic app name"
      run: |
        echo "Output [${{steps.output_step.outputs.logicAppName}}]"

    - name: Create project folder
      run: |
        mkdir output
        cp 'logicapps/host.json' 'output/'
        cp 'logicapps/connections.json' 'output/'
        cp -r 'logicapps/publisher' 'output/'

    - name: Easy Zip Files
      uses: papeloto/action-zip@v1
      with:
        dest: '${{ github.run_id }}.zip'
        files: output/

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{steps.output_step.outputs.LogicAppName}}
        package: '${{ github.run_id }}.zip'

