# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (classic) Build and Deploy Logic App. 

env:
  AZURE_LOGICAPP_PACKAGE_PATH: '.'
  RG_LA: ${{ vars.RG_PREFIX}}'app'

on:
  - workflow_dispatch 

jobs:
   logic_app_build: 
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

      # Deploy Bicep file
    - name: Deploy Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az deployment group create \
             --name 'bicep-deploy-'${{ github.run_id }} \
             --resource-group ${{env.RG_LA}} \
             --parameters bicep/main.dev.bicepparam

    - name: Get output
      id: output
      run: echo "::set-output name=LogicAppName::$(az deployment group show --name bicep-deploy-${{ github.run_id }} --resource-group ${{env.RG_LA}} --query properties.outputs.LogicAppName.value -o tsv)"

    - name: Get publish Profile
      id: fncapp
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{env.RG_LA}} `
              -Name ${{ steps.output.outputs.LogicAppName}}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Create project folder
      run: |
        mkdir output
        cp 'logicapps/host.json' 'output/'
        cp 'logicapps/connections.json' 'output/'
        cp -r 'logicapps/publisher' 'output/'

    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        dest: '${{ github.run_id }}.zip'
        files: output/

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{env.RG_LA}}
        package: '${{ github.run_id }}.zip'
        publish-profile: ${{steps.fncapp.outputs.profile}}

